version: '3'

services:
  frontend:
    image: applicationform-frontend:v1
    volumes:
      - ./frontend/applicant_data:/app/applicant_data
    build: 
      context: ./frontend
    ports:
      - "8501:8501"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
    entrypoint: ["streamlit", "run", "gui.py", "--server.port=8501", "--server.address=0.0.0.0"]

  backend-coordinator:
    image: applicationform-backend-coordinator:v1
    build:
      context: ./backend/coordinator
    ports:
      - "8000:8000"
    entrypoint: ["python3", "main.py", "0.0.0.0", "8000"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend-coordinator:8000/healthcheck", "||", "exit", "1"]
      interval: 1m30s
      timeout: 30s
      retries: 5

  backend-model:
    image: applicationform-backend-model:v1
    build:
      context: ./backend/model
    ports:
      - "8001:8001"
    entrypoint: ["python3", "main.py", "0.0.0.0", "8000"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend-model:8000/healthcheck", "||", "exit", "1"]
      interval: 1m30s
      timeout: 30s
      retries: 5

  application-minio:
    container_name: application-minio
    image: minio/minio:RELEASE.2020-12-03T00-03-10Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9000:9000"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-./volumes}/minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
networks:
  default:
    name: application-net
